apiVersion: v1
kind: Service
metadata:
  labels:
    app: gugotik-favorite-service
  name: gugotik-favorite-service
  namespace: gugotik-service-bundle
spec:
  ports:
    - name: grpc
      port: 37006
      protocol: TCP
      targetPort: 37006
  selector:
    name: gugotik-favorite-service
    branch: master
  type: ClusterIP