apiVersion: v1
kind: Service
metadata:
  labels:
    app: gugotik-feed-service
  name: gugotik-feed-service
  namespace: gugotik-service-bundle
spec:
  ports:
    - name: grpc
      port: 37004
      protocol: TCP
      targetPort: 37004
  selector:
    name: gugotik-feed-service
    branch: master
  type: ClusterIP